import React, { useState } from 'react';

const typeConfig = {
  exam: { bg: '#1a0808', border: '#4a1010', text: '#D85A30', icon: '📝' },
  study: { bg: '#081a10', border: '#0f3a1f', text: '#1D9E75', icon: '📚' },
  assignment: { bg: '#1a1000', border: '#4a3000', text: '#EF9F27', icon: '📋' },
};

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const DAYS = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];

export default function Calendar({ events: initialEvents }) {
  const today = new Date();
  const [currentMonth, setCurrentMonth] = useState(today.getMonth());
  const [currentYear, setCurrentYear] = useState(today.getFullYear());
  const [events, setEvents] = useState(initialEvents || []);
  const [showAddModal, setShowAddModal] = useState(false);
  const [showDetailModal, setShowDetailModal] = useState(null);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [form, setForm] = useState({ title: '', date: '', type: 'study', notes: '' });

  const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
  const firstDay = new Date(currentYear, currentMonth, 1).getDay();

  const getEventsForDay = (day) => {
    const dateStr = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    return events.filter(e => e.date === dateStr);
  };

  const handleAddEvent = () => {
    if (!form.title || !form.date) return;
    setEvents(prev => [...prev, { ...form }]);
    setForm({ title: '', date: '', type: 'study', notes: '' });
    setShowAddModal(false);
  };

  const openGoogleCalendar = (event) => {
    const dateStr = event.date ? event.date.replace(/-/g, '') : '20250101';
    const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.title)}&dates=${dateStr}/${dateStr}&details=${encodeURIComponent(event.notes || '')}`;
    window.open(url, '_blank');
  };

  const downloadICS = () => {
    const icsLines = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//Syllabus Success Engine//EN',
    ];
    events.forEach(e => {
      const d = e.date ? e.date.replace(/-/g, '') : '20250101';
      icsLines.push('BEGIN:VEVENT');
      icsLines.push(`SUMMARY:${e.title}`);
      icsLines.push(`DTSTART:${d}`);
      icsLines.push(`DTEND:${d}`);
      icsLines.push(`DESCRIPTION:${e.notes || ''}`);
      icsLines.push('END:VEVENT');
    });
    icsLines.push('END:VCALENDAR');
    const blob = new Blob([icsLines.join('\n')], { type: 'text/calendar' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'study-schedule.ics'; a.click();
  };

  const openEmailDraft = () => {
    const examEvents = events.filter(e => e.type === 'exam');
    const subject = `Weekly Study Prep — ${MONTHS[currentMonth]} ${currentYear}`;
    const body = `Hi,\n\nHere is your weekly study prep summary:\n\n` +
      `📅 UPCOMING EVENTS:\n` +
      events.slice(0, 5).map(e => `• ${e.title} — ${e.date || e.date}`).join('\n') +
      `\n\n📝 EXAMS TO PREPARE FOR:\n` +
      (examEvents.length > 0 ? examEvents.map(e => `• ${e.title} on ${e.date}\n  Notes: ${e.notes || 'N/A'}`).join('\n') : 'No exams scheduled') +
      `\n\n💡 NOVA's TIP:\nStay consistent! Focus on high-intensity weeks and review tough topics daily.\n\nGenerated by Syllabus Success Engine 🚀`;
    window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`, '_blank');
    setShowEmailModal(false);
  };

  const prevMonth = () => {
    if (currentMonth === 0) { setCurrentMonth(11); setCurrentYear(y => y - 1); }
    else setCurrentMonth(m => m - 1);
  };

  const nextMonth = () => {
    if (currentMonth === 11) { setCurrentMonth(0); setCurrentYear(y => y + 1); }
    else setCurrentMonth(m => m + 1);
  };

  const inputStyle = {
    width: '100%', backgroundColor: '#0a0a0a', color: 'white',
    padding: '0.75rem 1rem', borderRadius: '8px', border: '1px solid #222',
    outline: 'none', fontFamily: 'DM Sans, sans-serif', fontSize: '0.9rem',
    boxSizing: 'border-box'
  };

  const labelStyle = {
    color: '#888', fontSize: '0.75rem', fontFamily: 'Space Mono, monospace',
    display: 'block', marginBottom: '0.5rem',
    textTransform: 'uppercase', letterSpacing: '0.05em'
  };

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#0a0a0a', padding: '2rem', fontFamily: 'DM Sans, sans-serif' }}>
      <div style={{ maxWidth: '900px', margin: '0 auto' }}>

        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
          <div>
            <h1 style={{ fontFamily: 'Space Mono, monospace', color: '#1D9E75', fontSize: '1.4rem', fontWeight: 'bold', letterSpacing: '2px' }}>
              STUDY CALENDAR
            </h1>
            <p style={{ color: '#444', fontSize: '0.75rem', fontFamily: 'Space Mono, monospace' }}>
              {events.length} EVENTS SCHEDULED
            </p>
          </div>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button onClick={() => setShowEmailModal(true)} style={{
              backgroundColor: 'transparent', color: '#1D9E75',
              border: '1px solid #1D9E75', padding: '0.65rem 1.25rem',
              borderRadius: '8px', cursor: 'pointer',
              fontFamily: 'Space Mono, monospace', fontSize: '0.75rem', letterSpacing: '1px'
            }}>✉ WEEKLY EMAIL</button>
            <button onClick={downloadICS} style={{
              backgroundColor: 'transparent', color: '#EF9F27',
              border: '1px solid #EF9F27', padding: '0.65rem 1.25rem',
              borderRadius: '8px', cursor: 'pointer',
              fontFamily: 'Space Mono, monospace', fontSize: '0.75rem', letterSpacing: '1px'
            }}>↓ EXPORT .ICS</button>
            <button onClick={() => setShowAddModal(true)} style={{
              backgroundColor: '#1D9E75', color: '#0a0a0a',
              border: 'none', padding: '0.65rem 1.25rem',
              borderRadius: '8px', cursor: 'pointer',
              fontFamily: 'Space Mono, monospace', fontWeight: 'bold',
              fontSize: '0.75rem', letterSpacing: '1px'
            }}>+ ADD EVENT</button>
          </div>
        </div>

        {/* Month Navigation */}
        <div style={{
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          marginBottom: '1rem', backgroundColor: '#111111',
          padding: '1rem 1.5rem', borderRadius: '12px', border: '1px solid #1a1a1a'
        }}>
          <button onClick={prevMonth} style={{
            background: '#1a1a1a', border: '1px solid #333', color: '#888',
            width: '36px', height: '36px', borderRadius: '8px', cursor: 'pointer', fontSize: '1rem'
          }}>←</button>
          <h2 style={{ fontFamily: 'Space Mono, monospace', color: '#fff', fontSize: '1rem', letterSpacing: '2px' }}>
            {MONTHS[currentMonth].toUpperCase()} {currentYear}
          </h2>
          <button onClick={nextMonth} style={{
            background: '#1a1a1a', border: '1px solid #333', color: '#888',
            width: '36px', height: '36px', borderRadius: '8px', cursor: 'pointer', fontSize: '1rem'
          }}>→</button>
        </div>

        {/* Day Headers */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '4px', marginBottom: '4px' }}>
          {DAYS.map(d => (
            <div key={d} style={{
              textAlign: 'center', padding: '8px',
              fontFamily: 'Space Mono, monospace', fontSize: '11px', color: '#444'
            }}>{d}</div>
          ))}
        </div>

        {/* Calendar Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '4px' }}>
          {Array.from({ length: firstDay }).map((_, i) => (
            <div key={`e-${i}`} style={{ height: '90px' }} />
          ))}
          {Array.from({ length: daysInMonth }).map((_, i) => {
            const day = i + 1;
            const dayEvents = getEventsForDay(day);
            const isToday = day === today.getDate() && currentMonth === today.getMonth() && currentYear === today.getFullYear();
            return (
              <div
                key={day}
                onClick={() => {
                  const dateStr = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
                  if (dayEvents.length > 0) setShowDetailModal(dayEvents);
                  else { setForm(f => ({ ...f, date: dateStr })); setShowAddModal(true); }
                }}
                style={{
                  height: '90px',
                  backgroundColor: isToday ? '#0d1f19' : '#111111',
                  border: isToday ? '1px solid #1D9E75' : '1px solid #1a1a1a',
                  borderRadius: '8px', padding: '6px', cursor: 'pointer',
                  transition: 'all 0.15s', overflow: 'hidden'
                }}
                onMouseEnter={e => e.currentTarget.style.border = '1px solid #333'}
                onMouseLeave={e => e.currentTarget.style.border = isToday ? '1px solid #1D9E75' : '1px solid #1a1a1a'}
              >
                <div style={{
                  fontFamily: 'Space Mono, monospace', fontSize: '11px',
                  color: isToday ? '#1D9E75' : '#555', marginBottom: '4px'
                }}>{day}</div>
                {dayEvents.slice(0, 2).map((ev, ei) => {
                  const cfg = typeConfig[ev.type] || typeConfig.study;
                  return (
                    <div key={ei} style={{
                      backgroundColor: cfg.bg, border: `1px solid ${cfg.border}`,
                      borderRadius: '4px', padding: '2px 5px', marginBottom: '2px',
                      fontSize: '9px', color: cfg.text,
                      fontFamily: 'Space Mono, monospace',
                      overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis'
                    }}>{ev.title}</div>
                  );
                })}
                {dayEvents.length > 2 && (
                  <div style={{ fontSize: '9px', color: '#444', fontFamily: 'Space Mono, monospace' }}>
                    +{dayEvents.length - 2} more
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Legend */}
        <div style={{ display: 'flex', gap: '1.5rem', justifyContent: 'center', marginTop: '1.5rem' }}>
          {Object.entries(typeConfig).map(([type, config]) => (
            <div key={type} style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <div style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: config.text }} />
              <span style={{ color: '#444', fontSize: '0.75rem', fontFamily: 'Space Mono, monospace', textTransform: 'uppercase' }}>{type}</span>
            </div>
          ))}
        </div>
      </div>

      {/* ADD EVENT MODAL */}
      {showAddModal && (
        <div onClick={() => setShowAddModal(false)} style={{
          position: 'fixed', inset: 0, backgroundColor: '#000000cc',
          display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '2rem'
        }}>
          <div onClick={e => e.stopPropagation()} style={{
            backgroundColor: '#111111', borderRadius: '16px', padding: '2rem',
            maxWidth: '440px', width: '100%', border: '1px solid #1D9E75',
            boxShadow: '0 0 40px #1D9E7522'
          }}>
            <h3 style={{ fontFamily: 'Space Mono, monospace', color: '#1D9E75', fontSize: '1rem', marginBottom: '1.5rem', letterSpacing: '1px' }}>
              + ADD NEW EVENT
            </h3>

            <div style={{ marginBottom: '1rem' }}>
              <label style={labelStyle}>Event Title</label>
              <input value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))}
                placeholder="e.g. Final Exam" style={inputStyle} />
            </div>

            <div style={{ marginBottom: '1rem' }}>
              <label style={labelStyle}>Date</label>
              <input type="date" value={form.date} onChange={e => setForm(f => ({ ...f, date: e.target.value }))}
                style={{ ...inputStyle, colorScheme: 'dark' }} />
            </div>

            <div style={{ marginBottom: '1rem' }}>
              <label style={labelStyle}>Type</label>
              <select value={form.type} onChange={e => setForm(f => ({ ...f, type: e.target.value }))}
                style={{ ...inputStyle, colorScheme: 'dark' }}>
                <option value="study">📚 Study</option>
                <option value="exam">📝 Exam</option>
                <option value="assignment">📋 Assignment</option>
              </select>
            </div>

            <div style={{ marginBottom: '1.5rem' }}>
              <label style={labelStyle}>Notes</label>
              <textarea value={form.notes} onChange={e => setForm(f => ({ ...f, notes: e.target.value }))}
                placeholder="Optional notes..." rows={3}
                style={{ ...inputStyle, resize: 'vertical', lineHeight: '1.6' }} />
            </div>

            <div style={{ display: 'flex', gap: '0.75rem' }}>
              <button onClick={handleAddEvent} style={{
                flex: 1, backgroundColor: '#1D9E75', color: '#0a0a0a',
                border: 'none', padding: '0.875rem', borderRadius: '8px', cursor: 'pointer',
                fontFamily: 'Space Mono, monospace', fontWeight: 'bold', fontSize: '0.85rem'
              }}>SAVE EVENT</button>
              <button onClick={() => setShowAddModal(false)} style={{
                flex: 1, backgroundColor: 'transparent', color: '#555',
                border: '1px solid #333', padding: '0.875rem', borderRadius: '8px',
                cursor: 'pointer', fontFamily: 'Space Mono, monospace', fontSize: '0.85rem'
              }}>CANCEL</button>
            </div>
          </div>
        </div>
      )}

      {/* EVENT DETAIL MODAL */}
      {showDetailModal && (
        <div onClick={() => setShowDetailModal(null)} style={{
          position: 'fixed', inset: 0, backgroundColor: '#000000cc',
          display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '2rem'
        }}>
          <div onClick={e => e.stopPropagation()} style={{
            backgroundColor: '#111111', borderRadius: '16px', padding: '2rem',
            maxWidth: '480px', width: '100%', border: '1px solid #1a1a1a',
            maxHeight: '80vh', overflowY: 'auto'
          }}>
            <h3 style={{ fontFamily: 'Space Mono, monospace', color: '#1D9E75', fontSize: '1rem', marginBottom: '1.5rem', letterSpacing: '1px' }}>
              EVENTS
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginBottom: '1.5rem' }}>
              {showDetailModal.map((event, i) => {
                const cfg = typeConfig[event.type] || typeConfig.study;
                return (
                  <div key={i} style={{
                    backgroundColor: cfg.bg, border: `1px solid ${cfg.border}`,
                    borderRadius: '12px', padding: '1rem'
                  }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                      <p style={{ color: '#fff', fontWeight: '600', fontSize: '0.95rem' }}>{event.title}</p>
                      <span style={{
                        backgroundColor: cfg.text + '22', color: cfg.text,
                        padding: '0.2rem 0.6rem', borderRadius: '999px',
                        fontSize: '0.7rem', fontFamily: 'Space Mono, monospace', textTransform: 'uppercase'
                      }}>{event.type}</span>
                    </div>
                    {event.notes && <p style={{ color: '#555', fontSize: '0.82rem', marginBottom: '0.75rem' }}>{event.notes}</p>}
                    <button
                      onClick={() => openGoogleCalendar(event)}
                      style={{
                        backgroundColor: 'transparent', color: '#1D9E75',
                        border: '1px solid #1D9E75', padding: '0.4rem 1rem',
                        borderRadius: '6px', cursor: 'pointer',
                        fontFamily: 'Space Mono, monospace', fontSize: '0.72rem'
                      }}>📅 ADD TO GOOGLE CALENDAR</button>
                  </div>
                );
              })}
            </div>
            <button onClick={() => setShowDetailModal(null)} style={{
              width: '100%', backgroundColor: '#1D9E75', color: '#0a0a0a',
              padding: '0.75rem', borderRadius: '8px', border: 'none',
              cursor: 'pointer', fontFamily: 'Space Mono, monospace',
              fontWeight: 'bold', fontSize: '13px', letterSpacing: '1px'
            }}>CLOSE</button>
          </div>
        </div>
      )}

      {/* WEEKLY EMAIL MODAL */}
      {showEmailModal && (
        <div onClick={() => setShowEmailModal(false)} style={{
          position: 'fixed', inset: 0, backgroundColor: '#000000cc',
          display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '2rem'
        }}>
          <div onClick={e => e.stopPropagation()} style={{
            backgroundColor: '#111111', borderRadius: '16px', padding: '2rem',
            maxWidth: '440px', width: '100%', border: '1px solid #1D9E75',
            boxShadow: '0 0 40px #1D9E7522'
          }}>
            <div style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
              <div style={{ fontSize: '2.5rem', marginBottom: '0.75rem' }}>✉️</div>
              <h3 style={{ fontFamily: 'Space Mono, monospace', color: '#1D9E75', fontSize: '1rem', letterSpacing: '1px', marginBottom: '0.5rem' }}>
                WEEKLY PREP EMAIL
              </h3>
              <p style={{ color: '#555', fontSize: '0.85rem', lineHeight: '1.6' }}>
                NOVA will auto-draft a weekly prep email summarizing your tough topics and upcoming events
              </p>
            </div>

            <div style={{ backgroundColor: '#0a0a0a', borderRadius: '10px', padding: '1rem', marginBottom: '1.5rem', border: '1px solid #1a1a1a' }}>
              <p style={{ fontFamily: 'Space Mono, monospace', fontSize: '11px', color: '#1D9E75', marginBottom: '8px' }}>EMAIL WILL INCLUDE:</p>
              {['📅 All upcoming events this month', '📝 Exam preparation reminders', '💡 NOVA\'s study tips', '🔥 High intensity week alerts'].map((item, i) => (
                <p key={i} style={{ color: '#888', fontSize: '0.82rem', marginBottom: '4px' }}>{item}</p>
              ))}
            </div>

            <div style={{ display: 'flex', gap: '0.75rem' }}>
              <button onClick={openEmailDraft} style={{
                flex: 1, backgroundColor: '#1D9E75', color: '#0a0a0a',
                border: 'none', padding: '0.875rem', borderRadius: '8px', cursor: 'pointer',
                fontFamily: 'Space Mono, monospace', fontWeight: 'bold', fontSize: '0.82rem', letterSpacing: '1px'
              }}>OPEN IN GMAIL →</button>
              <button onClick={() => setShowEmailModal(false)} style={{
                flex: 1, backgroundColor: 'transparent', color: '#555',
                border: '1px solid #333', padding: '0.875rem', borderRadius: '8px',
                cursor: 'pointer', fontFamily: 'Space Mono, monospace', fontSize: '0.85rem'
              }}>CANCEL</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}